name: Development - Metadata Driven Architecture - Core Library

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "22.6.0"

      - name: Install dependencies, test and build 🔧
        run: |
          npm i --legacy-peer-deps
          npm run test
          npm run build
