name: Development - Metadata Driven Architecture - Core Library

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Install dependencies, test and build 🔧
        run: |
          npm i
          npm run test
          npm run build
