name: Release - Metadata Driven Architecture - Core Library

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "22.6.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies, test and build 🔧
        id: deploy
        run: |
          npm install -g pnpm
          pnpm i
          pnpm run test
          pnpm run build

      - name: Publish package on NPM 📦
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
